Improve questions
CS3219-AY2425S1/cs3219-ay2425s1-project-g03 pull request #49
Opened 2024-10-01 03:34 UTC by samuelim01

## Description

Wrap delete questions into single network round trip and ensure questions table is responsive

## Checklist

- [x] I have updated documentation
- [ ] All tests passing

## Screenshots (if applicable)

2024-10-01 06:50 UTC, KhoonSun47 requested changes
Looks good for the backend! Just need to do some minor changes for the README.

2024-10-01 06:56 UTC, samuelim01 commented on services/question/README.md
> +| 400 (Bad Request)           | The `id` was not specified                     |
aights 👍

2024-10-01 11:50 UTC, limcaaarl requested changes
Other than the minor typo, everything seems good and work fine 👍👍

2024-10-01 11:50 UTC, limcaaarl commented on services/question/README.md
> +| 400 (Bad Request)           | The `id` was not specified                     |
I think this should be `ids` to match the param above.

2024-10-01 12:29 UTC, samuelim01 commented on services/question/README.md
> +| 400 (Bad Request)           | The `id` was not specified                     |
@KhoonSun47 I modified the parameters section above to be clearer, does that work?

2024-10-02 02:51 UTC, KhoonSun47 commented on services/question/README.md
> +| 400 (Bad Request)           | The `id` was not specified                     |
Yeap, it works, thanks :)

2024-10-02 02:52 UTC, KhoonSun47 approved these changes
LGTM!

2024-10-03 07:24 UTC, limcaaarl approved these changes

2024-10-03 07:26 UTC, merged